# Generated by Django 4.2.5 on 2023-10-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotoko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
