# Generated by Django 4.2.5 on 2023-11-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
