# Generated by Django 4.2.5 on 2023-11-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.IntegerField(),
        ),
    ]
