# Generated by Django 4.2.5 on 2023-11-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(default='Ghanaian', max_length=100),
        ),
    ]
